server:
  port: 8090
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ExpenseTrackerApp
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  messages:
    basename: i18n/messages
    fallback-to-system-locale: false

jwt:
  secret: 546A576E5A7234753778214125442A472D4B6150645367566B58703273357638